
version: '3'

services:
  centrifugo:
    image: centrifugo/centrifugo:latest
    volumes:
      - ./centrifugo.json:/centrifugo/config.json
    ports:
      - "9000:9000"
    command: centrifugo -c config.json
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - centrifugo
    restart: always
